<?php 
echo $this->formrecherche;

if($this->formre){?>
<center><table border="1">
<tr bgcolor="#00ff00"> 
        <td>Nom</td>
		<td>Nom de l'exigence</td>
		<td>Etat d'avancement</td>
		<td>Supprimer</td>
		<td>Modifier</td>
</tr>
<?php
 $at = new Application_Model_DbTable_Exigences();
//foreach permet de parcourir tous les enregistrement d'une base de données
foreach ($this->formre  as $user):?>
<tr>
		<td> <?php
		//"escape" est utilisée pour supprimer les espaces s'ils existent
echo $this->escape($user->nom);
?></td>
		<td> <?php
foreach ($at->fetchAll() as $user1):
if($this->escape($user->id_exigence)==($user1->id))
echo $user1->nom;
endforeach;
?></td>
<td> <?php
		//"escape" est utilisée pour supprimer les espaces s'ils existent
echo $this->escape($user->etat);
?></td>
<td> <a href="<?php echo $this->url(array('controller'=>'Tache','action'=>'delete','id'=>$user->id));?>">Supprimer</a></td>
<td> <a href="<?php echo $this->url(array('controller'=>'Tache','action'=>'edit','id'=>$user->id));?>">Modifier</a></td>
	</tr>

	<?php endforeach; ?>

</table>
<a href="<?php echo $this->url (

								// notre controlleur est "Utilisateur" et notre action est "inscri"
								array( 'controller'=>'Tache', 
									   'action'=>'inscription'))?>"> Ajouter</a>
<a href="<?php echo $this->url (

								// notre controlleur est "Utilisateur" et notre action est "inscri"
								array( 'controller'=>'Tache', 
									   'action'=>'recherche'))?>"> Rechercher</a></center>
		
<?php }?>