<?php
/**
 * Default Layout
 *
 * @author
 * @version
 */

echo '<?xml version="1.0" encoding="UTF-8" ?>';
echo $this->doctype()
?>

<html>

    <head>
        <meta http-equiv="Content-Type" content="text/html;
        charset=UTF-8" />
        <link rel="stylesheet" type="text/css" href="<?php echo
        $this->baseUrl();?>/styles/design.css" />
        <?php
        echo $this->headTitle();
        echo $this->headScript();
        echo $this->headStyle();
        ?>
    </head>

    <body>
         <div id="header">
           <center><h1>Gestion des exigences</h1></center>
            <ul id="nav">
                <li><a href="<?php echo $this->url (

								// notre controlleur est "Utilisateur" et notre action est "inscri"
								array( 'controller'=>'Manager', 
									   'action'=>'acceuil'))?>">Accueil</a></li>
                <li><a href="<?php echo $this->url (

								// notre controlleur est "Utilisateur" et notre action est "inscri"
								array( 'controller'=>'Manager', 
									   'action'=>'lst'))?>">Gestion des manager</a></li>
                <li><a  href="<?php echo $this->url (

								// notre controlleur est "Utilisateur" et notre action est "inscri"
								array( 'controller'=>'Collaborateur', 
									   'action'=>'lst'))?>">Gestion des collaborateurs</a></li>
                <li><a href="<?php echo $this->url (

								// notre controlleur est "Utilisateur" et notre action est "inscri"
								array( 'controller'=>'Projet', 
									   'action'=>'lst'))?>">Gestions des projets</a></li>
            </ul>
        </div>

        <div id="container">
         <?php echo $this->contenu ;?>
            <div id="content">
            <h1><?php echo $this->placeholder('title')
            ?></h1>
            
           
            </div>
           
            
      </div>
        <div id="footer">
            <p class="validate"><a href="http://validator.w3.org/check?uri=referer">XHTML</a>
            |
            <a href="http://jigsaw.w3.org/css-validator/">CSS</a>
            | <a href="#content">Top</a></p>
            <p><a href="www.lyrixx.info">© Pineau Gr&eacute;goire</a></p>
            
        </div>

        <br />
        <br />
    </body>

</html>