
<!-- Nous créons un tableau qui va lister tous les utilisateurs -->
<center><h1>Liste des exigences</h1>
<table border="1px">
	<tr bgcolor="#00ff00">
		<td>Nom</td>
		<td>Description</td>
		<td>Nom du Manager</td>
		<td>Supprimer</td>
	</tr>
<?php
 $at = new Application_Model_DbTable_Manager();
//foreach permet de parcourir tous les enregistrement d'une base de données
foreach ($this->users as $user):?>
<tr>
		<td> <?php
		//"escape" est utilisée pour supprimer les espaces s'ils existent
echo $this->escape($user->nom);
?></td>
		<td> <?php
echo $this->escape($user->description);
?></td>
		<td> <?php
foreach ($at->fetchAll() as $user1):
if($this->escape($user->id_manager)==($user1->id))
echo $user1->nom;
endforeach;
?></td>
<td> <a href="<?php echo $this->url(array('controller'=>'Projet','action'=>'delete','id'=>$user->id));?>">Supprimer</a></td>
	</tr>
	<?php endforeach; ?>

</table>
<a href="<?php echo $this->url (

								// notre controlleur est "Utilisateur" et notre action est "inscri"
								array( 'controller'=>'Projet', 
									   'action'=>'inscription'))?>"> Ajouter</a>
<a href="<?php echo $this->url (

								// notre controlleur est "Utilisateur" et notre action est "inscri"
								array( 'controller'=>'Projet', 
									   'action'=>'recherche'))?>"> Rechercher</a></center>
		




