<?php 
echo $this->formrecherche;

if($this->formre){?>
<center><table border="1">
<tr bgcolor="#00ff00"> 
<td> Nom </td>
<td> Description </td>
<td> Id_Manager </td>
<td> supprimer </td>
</tr>
<?php
foreach ($this->formre as $ligne):?>
<tr> 
<td> <?php echo  $this->escape($ligne->nom);?></td>
<td> <?php echo $this->escape($ligne->description);?></td>
<td> <?php echo $this->escape($ligne->id_manager);?></td>
<td> <a href="<?php echo $this->url(array('controller'=>'Projet','action'=>'delete','id'=>$ligne->id));?>">Supprimer</a></td>
</tr>

<?php endforeach;?>
</table></center>
<?php
} ?>