<html>

    <head>
        <meta http-equiv="Content-Type" content="text/html;
        charset=UTF-8" />
        <link rel="stylesheet" type="text/css" href="<?php echo
        $this->baseUrl();?>/styles/design.css" />
        <?php
        echo $this->headTitle();
        echo $this->headScript();
        echo $this->headStyle();
        ?>
    </head>

    <body>
         <div id="header">
           <center><h1>Gestion des exigences</h1></center>
            <ul id="nav1">
                <li><a href="http://www.lemonde.fr/">Nouvelles</a></li>
                <li><a href="http://www.youtube.com/">Videos</a></li>
                <li><a  href="http://www.esprit.ens.tn/test/v3/index.php?lang=fr">Esprit</a></li>
                <li><a href="https://www.google.tn/">Google</a></li>
            </ul>
        </div>
<?php 
echo $this->formrecherche;

if($this->formre){?>
<center><table border="1">
<tr bgcolor="#00ff00"> 
<td> Nom </td>
<td> Description </td>
<td> Id_Manager </td>
<td> supprimer </td>
</tr>
<?php
foreach ($this->formre as $ligne):?>
<tr> 
<td> <?php echo  $this->escape($ligne->nom);?></td>
<td> <?php echo $this->escape($ligne->description);?></td>
<td> <?php echo $this->escape($ligne->id_manager);?></td>
<td> <a href="<?php echo $this->url(array('controller'=>'Projet','action'=>'delete','id'=>$ligne->id));?>">Supprimer</a></td>
</tr>

<?php endforeach;?>
</table></center>
<?php
} ?>
